manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Reinmuth66
      url-base: https://github.com/Reinmuth66/
    - name: zettaface
      url-base: https://github.com/zettaface
    - name: eswai # ここを追加
      url-base: https://github.com/eswai
    # - name: oleksandrmaslov
    #   url-base: https://github.com/oleksandrmaslov
  projects:
    - name: zmk
      remote: zmkfirmware
    - revision: main
      revision: v0.3
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: Reinmuth66
      revision: v3
    - name: zmk-analog-input-driver
      remote: Reinmuth66
      revision: main
    - name: zmk-input-processor-keybind
      remote: zettaface
      revision: main
    - name: zmk-naginata # ここを追加
      remote: eswai
      revision: main
    # - name: zmk-pointing-acceleration
    #   remote: oleksandrmaslov
    #   revision: main
  self:
    path: config
