manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Reinmuth66
      url-base: https://github.com/Reinmuth66/
    - name: zettaface
      url-base: https://github.com/zettaface
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: Reinmuth66
      revision: main
    # Reinmuth66 の zmk-analog-input-driver を削除
    # - name: zmk-analog-input-driver
    #   remote: Reinmuth66
    #   revision: main
    - name: zmk-input-processor-keybind
      remote: zettaface
      revision: main
    - name: zmk-analog-input-driver # badjeff のバージョンを使用
      remote: badjeff
      revision: main
  self:
    path: config
